In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data=pd.read_csv("deliveries.csv")
###data2=pd.read_csv("ex2data2.csv")

data1.head()
###data2.head()

#%matplotlib inline 
#colors=np.where(data1.Accepted >0 ,'r','k')

       Exam1      Exam2  Accepted
0  34.623660  78.024693         0
1  30.286711  43.894998         0
2  35.847409  72.902198         0
3  60.182599  86.308552         1
4  79.032736  75.344376         1

In [2]:
info=np.where(data1.Accepted>0)

In [3]:
info

(array([ 3,  4,  6,  7,  8,  9, 12, 13, 15, 16, 18, 19, 21, 24, 25, 26, 30,
        31, 33, 37, 40, 42, 46, 47, 48, 49, 50, 51, 52, 56, 58, 59, 60, 66,
        68, 69, 71, 72, 73, 74, 75, 76, 77, 80, 81, 82, 83, 84, 85, 87, 88,
        90, 91, 93, 94, 95, 96, 97, 98, 99], dtype=int64),)

In [6]:
pd.read_csv('ex2data1.csv', usecols=['Exam1','Exam2'])

        Exam1      Exam2
0   34.623660  78.024693
1   30.286711  43.894998
2   35.847409  72.902198
3   60.182599  86.308552
4   79.032736  75.344376
5   45.083277  56.316372
6   61.106665  96.511426
7   75.024746  46.554014
8   76.098787  87.420570
9   84.432820  43.533393
10  95.861555  38.225278
11  75.013658  30.603263
12  82.307053  76.481963
13  69.364589  97.718692
14  39.538339  76.036811
15  53.971052  89.207350
16  69.070144  52.740470
17  67.946855  46.678574
18  70.661510  92.927138
19  76.978784  47.575964
20  67.372028  42.838438
21  89.676776  65.799366
22  50.534788  48.855812
23  34.212061  44.209529
24  77.924091  68.972360
25  62.271014  69.954458
26  80.190181  44.821629
27  93.114389  38.800670
28  61.830206  50.256108
29  38.785804  64.995681
..        ...        ...
70  32.722833  43.307173
71  64.039320  78.031688
72  72.346494  96.227593
73  60.457886  73.094998
74  58.840956  75.858448
75  99.827858  72.369252
76  47.264269  88.475865
77  50.458160  75.809860
78  60.455556  42.508409
79  82.226662  42.719879
80  88.913896  69.803789
81  94.834507  45.694307
82  67.319257  66.589353
83  57.238706  59.514282
84  80.366756  90.960148
85  68.468522  85.594307
86  42.075455  78.844786
87  75.477702  90.424539
88  78.635424  96.647427
89  52.348004  60.769505
90  94.094331  77.159105
91  90.448551  87.508792
92  55.482161  35.570703
93  74.492692  84.845137
94  89.845807  45.358284
95  83.489163  48.380286
96  42.261701  87.103851
97  99.315009  68.775409
98  55.340018  64.931938
99  74.775893  89.529813

[100 rows x 2 columns]

In [7]:
data1.loc[(data1["Accepted"]='info']

SyntaxError: invalid syntax (<ipython-input-7-636300e2b170>, line 1)